name: qiskitazurequantum
channels:
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.7
  - pip>=21.1.3
  - pytest>=6.2.4
  - azure-core>=1.14.0
  - azure-identity>=1.6.0
  - azure-storage-blob>=12.8.1
  - azure-mgmt-core>=1.2.2
  - pip:
    - -e ../azure-quantum
    - azure-devtools>=1.2.0
    - qiskit-ionq>=0.1.4
    - qiskit-terra>=0.18.0
